// apps/svelte/app/components/Home.svelte
<page>
    <actionBar title="Home" />
    <stackLayout>
        <label class="info text-4xl">
            <formattedString>
                <span class="fas" text="&#xf135;" />
                <span class="text-primary-dark font-bold" text=" {message}" />
            </formattedString>
        </label>
        <button
          class="btn btn-primary btn-rounded border-8"
          borderColor="{color}"
          text="SO MUCH FLAVOR!"
        ></button>
    </stackLayout>
</page>

<script lang="ts">
    import { getMinimumCycleCount, getColor } from '@flavorful/ui/core';

    let message: string = "Blank Svelte Native App"
    let phaseCount: number = 0;
    let color: string = "";

    const cycle = getMinimumCycleCount();
    setInterval(() => {
      if(phaseCount > cycle) {
        phaseCount = 0;
      }
      color = getColor(phaseCount++);
    }, 1000 / 120);
</script>

<style>
    .info {
        horizontal-align: center;
        vertical-align: center;
    }
</style>

// apps/angular/src/features/home/components/home.component.ts
import { Component } from '@angular/core';
import { setStatusBarColor } from '../../../utils';
import { getMinimumCycleCount, RGB2Color, getColor } from '@flavorful/ui/core';

@Component({
  moduleId: module.id,
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent {
  frequency = 0.05;
  count = 0;
  color;

  ngOnInit() {
    setStatusBarColor('dark', '#97d9e9');

    const cycle = getMinimumCycleCount(this.frequency);
    setInterval(() => {
      if(this.count > cycle) {
        this.count = 0;
      }
      this.color = getColor(this.count++, this.frequency);
    }, 1000 / 120)
  }
}

<ActionBar title="My App" class="action-bar" flat="true">
</ActionBar>
<StackLayout class="p-20">
  <Button
    class="btn btn-rounded btn-primary"
    style="border-width: 4;"
    [style.border-color]="color"
    text="So much FLAVOR!">
  </Button>
  <Label text="Enjoy" class="h1 text-center c-white text-primary"></Label>
</StackLayout>
