// apps/vue/app/components/Home.vue
<template>
  <Page>
    <ActionBar>
      <Label text="Home"/>
    </ActionBar>

    <StackLayout>
      <Label class="info">
        <FormattedString>
          <Span class="fas text-primary" text.decode="&#xf135; "/>
          <Span class="text-primary-dark" :text="message"/>
        </FormattedString>
      </Label>
      <Button
        class="btn btn-primary rounded-full border-8"
        :borderColor="color"
        text="SO MUCH FLAVOR!">
      </Button>
    </StackLayout>
  </Page>
</template>

<script lang="ts">
  import Vue from "nativescript-vue";
  import { getColor, getMinimumCycleCount } from '@flavorful/core';

  export default Vue.extend({
    computed: {
      color() {
        return 'red';
      },
      message() {
        return "Blank {N}-Vue app";
      }
    },
    data () {
      return {
        color: 'red',
        phaseCount: 0,
        cycle: getMinimumCycleCount()
      }
    },
    methods: {
      pollColor () {
        setInterval(() => {
          if(this.phaseCount > this.cycle) {
            this.phaseCount = 0;
          }
          this.color = getColor(this.phaseCount++);
        }, 1000 / 120)
      }
    },
    created () {
      this.pollColor()
    }
  });
</script>

<style scoped lang="scss">
  .info {
    font-size: 20;
    horizontal-align: center;
    vertical-align: center;
  }
</style>

// apps/svelte/app/components/Home.svelte
<page>
    <actionBar title="Home" />
    <stackLayout>
        <label class="info text-4xl">
            <formattedString>
                <span class="fas" text="&#xf135;" />
                <span class="text-primary-dark font-bold" text=" {message}" />
            </formattedString>
        </label>
        <button
          class="btn btn-primary rounded-full border-8"
          borderColor="{color}"
          text="SO MUCH FLAVOR!"
        ></button>
    </stackLayout>
</page>

<script lang="ts">
    import { getMinimumCycleCount, getColor } from '@flavorful/core';

    let message: string = "Blank Svelte Native App"
    let phaseCount: number = 0;
    let color: string = "";

    const cycle = getMinimumCycleCount();
    setInterval(() => {
      if(phaseCount > cycle) {
        phaseCount = 0;
      }
      color = getColor(phaseCount++);
    }, 1000 / 120);
</script>

<style>
    .info {
        horizontal-align: center;
        vertical-align: center;
    }
</style>
